# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cate_name', models.CharField(max_length=100)),
                ('cate_pid', models.IntegerField()),
                ('cate_level', models.IntegerField()),
                ('cate_path', models.SmallIntegerField()),
            ],
        ),
    ]
