# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170905_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cate_level',
            field=models.SmallIntegerField(),
        ),
    ]
